### ISSUE TITLE
front end

### ISSUE THREAD

**Issue by schlosta** [kxs1119/Detection-System#12]
- [x] **Install Jinja2**
  - [x] Run `pip install Jinja2`.
  - [x] Verify installation by running `python -c "import jinja2"`.

- [x] **Create a Basic Jinja2 Template**
  - [x] Create a template file (e.g., `template.html`) with simple HTML structure.
  - [x] Add a variable placeholder like `{{ name }}`.

- [x] **Add Variables for Deer Detection**
  - [x] Add `{{ latitude }}` and `{{ longitude }}` for geolocation data.
  - [x] Add `{{ detection_time }}` to display the time of detection.
  - [x] Add `{{ animal_type }}` to specify the type of animal detected (e.g., deer).
  - [x] Add `{{ detection_id }}` to uniquely identify each detection event.
  - [x] Add `{{ alert_count }}` to trigger an alert when the number of detections exceeds a set threshold.

**Comment by kxs1119** [comment]
Updated description of task

**Comment by kxs1119** [comment]
> * * [x] 
>     [x]  **Install Jinja2**
>     
>     * [x]  Run `pip install Jinja2`.* [x]  Verify installation by running `python -c "import jinja2"`.* [x] 
>     [x]  **Create a Basic Jinja2 Template**
>     
>     * [x]  Create a template file (e.g., `template.html`) with simple HTML structure.* [x]  Add a variable placeholder like `{{ name }}`.* [x] 
>     [x]  **Add Variables for Deer Detection**
>     
>     * [x]  Add `{{ latitude }}` and `{{ longitude }}` for geolocation data.* [x]  Add `{{ detection_time }}` to display the time of detection.* [x]  Add `{{ animal_type }}` to specify the type of animal detected (e.g., deer).* [x]  Add `{{ detection_id }}` to uniquely identify each detection event.* [x]  Add `{{ alert_count }}` to trigger an alert when the number of detections exceeds a set threshold.
