### ISSUE TITLE
Create Figma Wireframe and User Experience/Interface for application

### ISSUE THREAD

**Issue by kxs1119** [kxs1119/Detection-System#44]
## Goals
- Create mobile wireframes in Figma
- Focus on ease of use and clear design for users tracking deer detections
- Ensure all key user actions are accounted for (e.g., map navigation, viewing alerts, notifications)
- Design should support both light and dark mode for accessibility

## Acceptance Criteria
- [ ] Mobile wireframe is complete in Figma
- [ ] Wireframe includes all necessary screens (e.g., map screen, notifications, settings, etc.)
- [ ] Design flow reviewed with the team
- [ ] Figma file shared in project repository or linked

**Comment by kxs1119** [comment]
Added self to assist if needed or to review

**Comment by ReaperX1090** [comment]
Got outline created for the app and the navigation to each specific location. Just have to figure out how to implement the map API to it and how we want to configure it

**Comment by kxs1119** [comment]
> Got outline created for the app and the navigation to each specific location. Just have to figure out how to implement the map API to it and how we want to configure it

Looks great! Post a pic in slack when you feel good with it!
