### ISSUE TITLE
RESEARCH: Compare Flutter vs Expo Go for Mobile App Development

### ISSUE THREAD

**Issue by kxs1119** [kxs1119/Detection-System#48]
- [x] Research ease of development and setup (Flutter SDK vs Expo Go tools)
- [x] Compare push notifications (Firebase FCM vs Expo Go)
- [x] Compare performance and responsiveness
- [x] Evaluate community support and documentation

**Comment by kxs1119** [comment]
For comparing the push notification, you will be looking at what is easier to implement/develop to the application of firebase FCM vs Expo Go.

Push Notifications - Having a notification show up to be visible by the client/user

**Comment by ReaperX1090** [comment]
So by the looks of it, Flutter is a single codebase where mobile development would be much more appreciated being on a single user interface that is compatible with all IDE's available with a simple layout. With Expo Go, its a much simpler design for mobile development, mainly for beginners, however, it doesn't support native development as well. With Flutter, only one programming language is needed and its called Dart, an object oriented language.

**Comment by ReaperX1090** [comment]
Expo Go would also come along with bugs and other issues regarding push notifications to mobile phone as that is one of Expo Go's main issues as a simple mobile app development software

**Comment by ReaperX1090** [comment]
Flutter is more powerful and responsive with its push notifications and app development and overall looks like a better product to utilize

**Comment by ReaperX1090** [comment]
Firebase would also be a better option for notifications
