### ISSUE TITLE
Develop Basic UI for Displaying Detected Deer

### ISSUE THREAD

**Issue by kxs1119** [kxs1119/Detection-System#56]
### 1. **Understanding the Goal**
- You are tasked with creating an interface that **displays a list of deer locations** based on **mock data** (i.e., placeholder data for now, which will later be replaced by real API data).
- The UI will live in a file called `DeerListScreen.dart`.
- You want this list to **update dynamically** when the data changes.

#### a. **File Setup**
- Ensure you have a file named `DeerListScreen.dart` under the `lib/screens/` directory.
  - This file will contain the code to display the list of deer locations.

#### b. **Basic UI Structure**
- The UI will display a **list of items**, where each item corresponds to a deer location.
- You will start with **mock data** (some fake deer locations), which means you'll hardcode this data for now to simulate what it would look like when you fetch real data from an API.
- The list should follow the design guide you have, but for now, just keep it simple and focus on the layout.

#### c. **Hot Reload Setup**
- While working on your UI, **Flutter’s hot reload** will allow you to quickly see changes without restarting the app.
  - Ensure you can use **hot reload** as you make changes by pressing the **lightning bolt icon** or by using the terminal command for hot reload.
  - You will make small changes to the UI and see instant updates on your connected emulator or device.

#### d. **Dynamic List Behavior**
- The **mock data** will be displayed first. In the future, this list will need to change based on data fetched from an API.
- You need to make sure the UI updates **when the data changes** (even if it's just mock data for now). This means the list should respond to data changes and refresh to display new information if necessary.

#### e. **Styling**
- Make sure the layout follows the **design guide**.
  - For now, you can use basic layouts (like rows and columns) to display text that represents deer locations.
  - The styling can be refined later once the core functionality is working.

### 3. **Acceptance Criteria Recap**
- The UI is implemented in `DeerListScreen.dart` and displays the mock data.
- You have a **basic list view** that shows items (each item represents a deer location).
- **Hot reload** is working correctly for fast development.
- The UI responds to changes in the data (this will help in the future when real API data is integrated).

**Comment by ReaperX1090** [comment]
Added DeerListScreen file to lib/screen directory in flutter app
